### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by nvcken** [pyqt/python-qt5#15]
No files/directories in /tmp/pip-build-vOCnC2/python-qt5/pip-egg-info (from PKG-INFO)
What I missed ?

**Comment by mottosso** [comment]
We just updated the pip distribution, it's possible something went wrong.

Having a look now.

**Comment by mottosso** [comment]
Hmm, it works fine here.

Could you post the steps you took to produce the error, and the exact error?

Here is what I got.

```cmd
C:\Users\marcus>pip install python-qt5
Downloading/unpacking python-qt5
  Running setup.py (path:c:\users\marcus\appdata\local\temp\pip_build_marcus\pyt
hon-qt5\setup.py) egg_info for package python-qt5

Installing collected packages: python-qt5
  Running setup.py install for python-qt5

Successfully installed python-qt5
Cleaning up...

C:\Users\marcus>
```

**Comment by nvcken** [comment]
```
sudo pip install python-qt5
The directory '/home/ken/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ken/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting python-qt5
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading python-qt5-0.1.10.zip (57.5MB)
    99% |████████████████████████████████| 57.5MB 413kB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 291, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 704, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 317, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 304, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 469, in _prepare_file
    session=self.session)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 886, in _download_http_url
    _download_url(resp, link, content_file)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 621, in _download_url
    for chunk in progress_indicator(resp_read(4096), 4096):
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/ui.py", line 133, in iter
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 586, in resp_read
    decode_content=False):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/controller.py", line 224, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py", line 81, in dumps
    ).encode("utf8"),
MemoryError


```

**Comment by nvcken** [comment]
same error when not sudo.
My env
pip 7.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

**Comment by mottosso** [comment]
Ok, I see two problems.

1. This distribution is Windows-only.
2. There seems to be some ownership problems.
