### ISSUE TITLE
No module named sip

### ISSUE THREAD

**Issue by betty-crokker** [pyqt/python-qt5#65]
We have a third-party library that is delivered to us as a WHL file; that library uses this Qt5 module.  We are running using Python 2.7.  Our application runs beautifully inside PyCharm, but when we create an executable using pyinstaller, the resulting file crashes immediately, leaving this in the terminal window:
```
Qt: Untested Windows version 10.0 detected!
Traceback (most recent call last):
(snip)
  File "site-packages\RTL\face.py", line 12, in <module>
  File "C:\Users\employee\Documents\app\venv\Lib\site-packages\PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\RTL\Provider\provider.py", line 11, in <module>
  File "C:\Users\employee\Documents\app\venv\Lib\site-packages\PyInstaller/loader/pyimod03_importers.py", line 680, in load_module
    module = imp.load_module(fullname, fp, filename, ext_tuple)
ImportError: No module named sip
[28164] Failed to execute script Main

```
Is there something special that has to be done, either in the creation or the consumption of the WHL file, to get sip to install correctly?

**Comment by betty-crokker** [comment]
The third party has fixed the issue, not sure how.
